### ISSUE TITLE
Plugin resolution is not affected by DPI unlike VST3 counterpart

### ISSUE THREAD

**Issue by unplugred** [free-audio/clap-juce-extensions#131] opened 2023-05-22 03:38 UTC
https://github.com/unplugred/vsts/issues/1
When changing System -> Display -> Scale to be a non 100% value, the CLAP version stays in the same size, unlike the VST3 counterpart which scales properly.
This has broken a lot of my plugins who depend on DPI to get anti aliasing and canvas resolutions right.
Replicated on Windows as well as Linux,

**Comment by baconpaul** [comment] 2023-05-22 18:33
yes i was trying to fix this last week on linux and couldn't make the resize and scale behavior work. Thank you for raising it. Right now we do not pass the scale through correctly, but if we do, i get unstable sizing behavior in bitwig for resizable guis.

**Comment by baconpaul** [comment] 2024-04-15 23:56
@jatinchowdhury18 did you ever get anywhere looking at this?

I can look this later week when I'll have my lin/win box available, but @asb2m10 also flagged it to me as a deed blocker. I know you poked at it once.

I think the problem is we are just not passing gui_set_scale to the set Scale but, again, making that work with the gui_set_size and constrain size and constrainers just failed for me.

**Comment by jatinchowdhury18** [comment] 2024-04-16 16:15
Interesting... So I think the scale factor is being set correctly (like when I look at the text size between the VST3 and CLAP GUIs, it appears to be the same). However, I think the way the scale factor is being used to decide on the editor window size is incorrect.

That said, I'm only able to test on Windows at the moment, so if it seems like both the window size and scale factor are not being set properly on Linux, then that is likely a deeper problem.

**Comment by jatinchowdhury18** [comment] 2024-04-16 16:21
Interestingly, this issue doesn't seem to happen in Reaper (while it does in Bitwig Studio and the FL Studio beta).

For reference, I've been using this "Scale" menu to change my display scale factor. I'm guessing this is the same thing that @unplugred was testing with?

![image](https://github.com/free-audio/clap-juce-extensions/assets/13724188/8fd3bd5b-88ec-4265-901f-34db8bfb5a5f)

**Comment by unplugred** [comment] 2024-04-19 23:31
That is indeed what im testing with.
I replicated the issue in Reaper as well.

**Comment by unplugred** [comment] 2024-04-19 23:54
UPDATE: Recompiled with newer version of clap-juce-extension and issue seems to be resolved in reaper.
Cannot comment about other DAWs.

**Comment by baconpaul** [comment] 2024-04-20 02:09
I was gonna look bitwig ubuntu tomorrow morning. Will update here when I do

**Comment by baconpaul** [comment] 2024-04-20 11:22
OK so bitwig ubuntu with dexed at head and CJE pulled to head and I run the clap and the vst3 side by side at 125% scaling

the VST3 is 125% bigger than the clap.

lemme look

**Comment by baconpaul** [comment] 2024-04-20 11:56
Huh interesting so I poked at this some more

Surge XT is fine - the CLAP and VST3 are the same size ubuntu 125%. That also matches what @unplugred saw that jatin's fix (which looks good to me) is good

For some reason it's not working with Dexed. I have an instrumented version running and we are resizing Dexed bigger but it seems to get ignored somehow?

Peeking peeking. But I think the CJE are at least mostly correct if not fully correct.

**Comment by baconpaul** [comment] 2024-04-20 12:33
Grr i just banged my head off of this on ubuntu for 90 minutes and got nowhere.

For some reason the VST3 is just 1.5x larger than the CLAP in bitwig when I set the resolution to 1.25

I thought it might be a desktop scale factor applied, but it isn't. I logged the scales and sizes and we are doing the right thing (you can check out that branch with log messages https://github.com/baconpaul/clap-juce-extensions/tree/scale-logging here) but I'm not getting this one this morning.

If I just hardcode in a 1.5 extra scale factor, it works and the sizes are the same.

I even printed the 'presumed scale factor' in the plugin itself and both CLAP and VST3 say "2" but they have different sizes and render differently.

Frustrating. I'll keep looking.

**Comment by asb2m10** [comment] 2024-07-05 02:29
I think we can close this issue since I found out why Dexed doesn't change upon DPI change... Since Dexed was an early clap-juce adopter, @baconpaul programmatically fixed the DPI to 1 when it was running under clap because of early stage problems.

I still have weird behaviour upon DPI changes but it is not related to this specific issue. I think we can close this one if @unplugred says that it is fixed and I'll open one that is related to Dexed problems.

**Comment by unplugred** [comment] 2024-07-05 02:58
yup works fine on my end

**Closed** 2024-07-05 02:59 UTC
